version: "3.7"
services:
  arangodb_si:
    image: arangodb:3.6
    hostname: arangodb_si
    container_name: arangodb_single_instance
    ports:
      - "8529:8529"
    environment:
      ARANGO_ROOT_PASSWORD: arangodb
      ARANGO_STORAGE_ENGINE: rocksdb
    volumes:
      - ./arangodb3/single_instance:/var/lib/arangodb3:delegated
