version: "3.7"
services:
  arangodb_afa:
    image: arangodb:3.6
    hostname: arangodb_afa
    container_name: arangodb_active_failover_agency
    command: arangodb/arangodb-starter --agents.agency.supervision-grace-period=30 --starter.address=$IP --starter.mode=activefailover --starter.join=arango_afa,arango_afl,arango_aff --cluster.start-single=false
    ports:
      - "8532:8532"
    environment:
      ARANGO_ROOT_PASSWORD: arangodb
      ARANGO_STORAGE_ENGINE: rocksdb
    volumes:
      - ./arangodb3/active_failover_agency:/var/lib/arangodb3:delegated
  arangodb_afl:
    image: arangodb:3.6
    hostname: arangodb_afl
    container_name: arangodb_active_failover_leader
    command: arangodb/arangodb-starter --agents.agency.supervision-grace-period=30 --starter.address=$IP --starter.mode=activefailover --starter.join=arango_afa,arango_afl,arango_aff
    ports:
      - "8533:8533"
    environment:
      ARANGO_ROOT_PASSWORD: arangodb
      ARANGO_STORAGE_ENGINE: rocksdb
    volumes:
      - ./arangodb3/active_failover_leader:/var/lib/arangodb3:delegated
  arangodb_aff:
    image: arangodb:3.6
    hostname: arangodb_aff
    container_name: arangodb_active_failover_follower
    command: arangodb/arangodb-starter --agents.agency.supervision-grace-period=30 --starter.address=$IP --starter.mode=activefailover --starter.join=arango_afa,arango_afl,arango_aff
    ports:
      - "8534:8534"
    environment:
      ARANGO_ROOT_PASSWORD: arangodb
      ARANGO_STORAGE_ENGINE: rocksdb
    volumes:
      - ./arangodb3/active_failover_follower:/var/lib/arangodb3:delegated
