version: "3.7"
services:
  arangodb_ca:
    image: arangodb:3.6
    hostname: arangodb_ca
    container_name: arangodb_cluster_agency
    ports:
      - "8535:8535"
    environment:
      ARANGO_ROOT_PASSWORD: arangodb
      ARANGO_STORAGE_ENGINE: rocksdb
    volumes:
      - ./arangodb3/cluster_agency:/var/lib/arangodb3:delegated
  arangodb_cc:
    image: arangodb:3.6
    hostname: arangodb_cc
    container_name: arangodb_cluster_coordinator
    ports:
      - "8536:8536"
    environment:
      ARANGO_ROOT_PASSWORD: arangodb
      ARANGO_STORAGE_ENGINE: rocksdb
    volumes:
      - ./arangodb3/cluster_coordinator:/var/lib/arangodb3:delegated
  arangodb_cd:
    image: arangodb:3.6
    hostname: arangodb_cd
    container_name: arangodb_cluster_dbserver
    ports:
      - "8534:8534"
    environment:
      ARANGO_ROOT_PASSWORD: arangodb
      ARANGO_STORAGE_ENGINE: rocksdb
    volumes:
      - ./arangodb3/cluster_dbserver:/var/lib/arangodb3:delegated
