version: "3.7"
services:
  arangodb_msm:
    image: arangodb:3.6
    hostname: arangodb_msm
    container_name: arangodb_master_slave_master
    ports:
      - "8530:8530"
    environment:
      ARANGO_ROOT_PASSWORD: arangodb
      ARANGO_STORAGE_ENGINE: rocksdb
    volumes:
      - ./arangodb3/master_slave_master:/var/lib/arangodb3:delegated
  arangodb_mss:
    image: arangodb:3.6
    hostname: arangodb_mss
    container_name: arangodb_master_slave_slave
    ports:
      - "8531:8531"
    environment:
      ARANGO_ROOT_PASSWORD: arangodb
      ARANGO_STORAGE_ENGINE: rocksdb
    volumes:
      - ./arangodb3/master_slave_slave:/var/lib/arangodb3:delegated
